// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy__AfIrG-yR3vCd5I5hvXCSK73vUVhfI',
    appId: '1:904429586233:web:bb54b5a724e2f632190ae8',
    messagingSenderId: '904429586233',
    projectId: 'stocklite-5c598',
    authDomain: 'stocklite-5c598.firebaseapp.com',
    storageBucket: 'stocklite-5c598.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xa8tCsrr6SrOsXOGYpYHv8RfCjePDxo',
    appId: '1:904429586233:android:8104cdd8b00a9f7e190ae8',
    messagingSenderId: '904429586233',
    projectId: 'stocklite-5c598',
    storageBucket: 'stocklite-5c598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcNEas2CRCP86XLj8h5cl5PqnGSsgovEY',
    appId: '1:904429586233:ios:2eb690ac385c5914190ae8',
    messagingSenderId: '904429586233',
    projectId: 'stocklite-5c598',
    storageBucket: 'stocklite-5c598.firebasestorage.app',
    iosBundleId: 'com.example.stockLite',
  );
}
